### ISSUE TITLE
HTML дублирующие строки js файла

### ISSUE THREAD

**Issue by seferen** [Sharpovich/FotoRoom#1]
дублирующие подгрузки одних и тех же библиотек js рекомендую убрать, зачем грузить одно и то же.

**Comment by Sharpovich** [comment]
Согласен, это бессмысленно. 
Хотя вряд ли оно влияло бы на нагрузку, ведь если грузит одно, то второе за ненадобностью.
Но скорее всего я ошибаюсь.
Скорректировал

**Comment by seferen** [comment]
Если у тебя в коде указано что приложение должно загрузить в память то оно загрузит, а если дублирующий то будет перезагружать. Зачем выполнять одно и то же действие 2 раза
